name: beomy_tech_auth
description: "A new Flutter project."
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter

  auto_route: ^9.2.2
  auto_route_generator: ^9.0.0
  cupertino_icons: ^1.0.8
  firebase_core: ^3.9.0
  firebase_auth: ^5.2.4
  google_sign_in: ^6.2.2
  local_auth: ^2.3.0
  intl: ^0.19.0
  rxdart: ^0.28.0
  provider: ^6.1.2
  flutter_svg: ^2.0.5
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_gen_runner:
  build_runner:
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

flutter_gen:
  output: lib/generated/
  line_length: 80

  integrations:
    flutter_svg: true

flutter_intl:
  enabled: true
